"use client";

import { FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import type { Locale, PlaceSummary, Post } from "@/lib/api";
import { api, ProblemDetailError } from "@/lib/api";
import styles from "./community.module.css";

type Step="closed"|"edit"|"confirm"|"complete";
export default function PostComposer({ locale, places, prompt }: { locale: Locale; places: PlaceSummary[]; prompt: string }) {
  const [step,setStep]=useState<Step>("closed");const [type,setType]=useState("discussion");const [title,setTitle]=useState("");const [body,setBody]=useState("");const [placeId,setPlaceId]=useState("");const [rating,setRating]=useState("5");const [amount,setAmount]=useState("");const [currency,setCurrency]=useState("VND");const [unit,setUnit]=useState("item");const [safetyState,setSafetyState]=useState("safe_now");const [draft,setDraft]=useState<Post|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const router=useRouter();
  const structured=useMemo(()=>{const observed_at=new Date().toISOString();if(type==="review")return{overall_rating:Number(rating),visited_at:new Date().toISOString().slice(0,10)};if(type==="price_report")return{item:title,amount_minor:Number(amount),currency,unit,observed_at};if(type==="scam_report")return{current_safety_state:safetyState,observed_at};return undefined},[type,rating,amount,currency,unit,title,safetyState]);
  const saveDraft=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{const result=await api.createDraft({post_type:type,original_locale:locale,title:title.trim(),body:body.trim(),place_ids:placeId?[placeId]:undefined,region_id:places.find(p=>p.place_id===placeId)?.region_id,structured_data:structured});setDraft(result);setStep("confirm")}catch(e){setError(e instanceof ProblemDetailError?`${e.message}${e.requestId?` · ${e.requestId}`:""}`:"Không thể lưu bản nháp")}finally{setBusy(false)}};
  const publish=async()=>{if(!draft)return;setBusy(true);setError("");try{const published=await api.publishPost(draft.post_id);setDraft(published);setStep("complete");router.refresh()}catch(e){setError(e instanceof ProblemDetailError?e.message:"Không thể xuất bản")}finally{setBusy(false)}};
  const reset=()=>{setStep("closed");setTitle("");setBody("");setDraft(null);setError("")};
  if(step==="closed")return <section className={styles.composer} id="composer"><button className={styles.composerTrigger} onClick={()=>setStep("edit")} type="button"><span className={styles.avatar} aria-hidden>+</span><span>{prompt}</span></button></section>;
  if(step==="confirm"&&draft)return <section className={styles.composer} id="composer" aria-labelledby="draft-heading"><div className={styles.preview}><strong id="draft-heading">Xác nhận bản nháp</strong><span className={styles.badge}>{type}</span><h2 className={styles.postTitle}>{title}</h2><p>{body}</p>{type==="scam_report"&&<p className={styles.notice}>Báo cáo mẫu rủi ro sẽ được gửi kiểm duyệt và chưa công khai ngay.</p>}</div><div className={styles.composerActions}><button className={styles.button} onClick={()=>setStep("edit")} disabled={busy}>Chỉnh sửa</button><button className={styles.buttonPrimary} onClick={publish} disabled={busy}>{busy?"Đang gửi…":type==="scam_report"?"Gửi kiểm duyệt":"Xuất bản"}</button></div>{error&&<p className={styles.errorText} role="alert">{error}</p>}</section>;
  if(step==="complete")return <section className={styles.composer} id="composer"><p role="status">{draft?.moderation_status==="pending"?"Báo cáo đã được gửi kiểm duyệt.":"Bài viết đã được xuất bản."}</p><button className={styles.button} onClick={reset}>Tạo bài khác</button></section>;
  return <section className={styles.composer} id="composer"><form className={styles.composerForm} onSubmit={saveDraft}>
    <div className={styles.composerTop}><span className={styles.avatar} aria-hidden>T</span><div style={{flex:1}}><label className="sr-only" htmlFor="post-title">Tiêu đề</label><input id="post-title" className={styles.field} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Tiêu đề ngắn gọn" required maxLength={500}/></div></div>
    <label className="sr-only" htmlFor="post-body">Nội dung</label><textarea id="post-body" className={styles.textarea} value={body} onChange={e=>setBody(e.target.value)} placeholder={prompt} required maxLength={50000}/>
    <div className={styles.composerOptions}><label>Loại bài<select className={styles.select} value={type} onChange={e=>setType(e.target.value)}><option value="discussion">Thảo luận</option><option value="question">Câu hỏi</option><option value="review">Đánh giá</option><option value="price_report">Báo giá</option><option value="scam_report">Báo cáo mẫu rủi ro</option><option value="tip">Mẹo</option></select></label><label>Địa điểm<select className={styles.select} value={placeId} onChange={e=>setPlaceId(e.target.value)} required={["review","price_report","scam_report"].includes(type)}><option value="">Không gắn địa điểm</option>{places.map(place=><option key={place.place_id} value={place.place_id}>{place.name}</option>)}</select></label></div>
    {type==="review"&&<label>Đánh giá tổng thể<select className={styles.select} value={rating} onChange={e=>setRating(e.target.value)}>{[5,4,3,2,1].map(v=><option key={v}>{v}</option>)}</select></label>}
    {type==="price_report"&&<div className={styles.composerOptions}><label>Số tiền<input className={styles.field} inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value)} required/></label><label>Tiền tệ<input className={styles.field} value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())} maxLength={3} required/></label><label>Đơn vị<input className={styles.field} value={unit} onChange={e=>setUnit(e.target.value)} required/></label></div>}
    {type==="scam_report"&&<label>Tình trạng an toàn hiện tại<select className={styles.select} value={safetyState} onChange={e=>setSafetyState(e.target.value)}><option value="safe_now">Hiện đã an toàn</option><option value="needs_guidance">Cần hướng dẫn an toàn</option><option value="immediate_danger">Đang có nguy hiểm — mở SOS trước</option></select></label>}
    <p className={styles.notice}>Bước này chỉ lưu bản nháp. Bạn sẽ xem lại trước khi xuất bản.</p>{error&&<p className={styles.errorText} role="alert">{error}</p>}<div className={styles.composerActions}><button className={styles.button} type="button" onClick={reset}>Hủy</button><button className={styles.buttonPrimary} disabled={busy||!title.trim()||!body.trim()}>{busy?"Đang lưu…":"Lưu bản nháp"}</button></div>
  </form></section>;
}
